server:
  port: 9400
sftp.server:
  host: '192.168.1.6'#My mac address
  order:
    remotePath: "/outgoing/"
  password: Gbs02378
  port: 22
  update:
    deleteRemoteFiles: true
    filterExpr: "^.*.txt"
    localPath: "./build/sftp/incoming"
    pollingFrequency: 1000
    remotePath: "/Users/Ganesan/incoming"
  user: Ganesan

management:
  endpoints:
    web:
      exposure:
        include: '*'